VideoShare/ViewModels/Channel/ChannelAddEdit_vm.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace VideoShare.ViewModels.Channel
{
  public class ChannelAddEdit_vm
  {
    [Required]
    [Display(Name = "Channel name")]
    [RegularExpression("^[a-zA-Z]{3,15}", ErrorMessage = "Name must be between 3 and 15 characters long and can only contain letters (A-Z, a-z)")]
    public string Name { get; set; }
    [Required(ErrorMessage = "About field is required")]
    [StringLength(200, MinimumLength = 20, ErrorMessage = "About must be at least {2}, and maximum {1} characters")]
    [Display(Name = "About your channel")]
    public string About { get; set; }
    public List<ModelError_vm> Errors { get; set; } = new List<ModelError_vm>();
  }
}

VideoShare/Controllers/ChannelController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Newtonsoft.Json;
using System.Linq;
using System.Threading.Tasks;
using VideoShare.Core.Entities;
using VideoShare.Core.IRepo;
using VideoShare.Extensions;
using VideoShare.Utility;
using VideoShare.ViewModels;
using VideoShare.ViewModels.Channel;

namespace VideoShare.Controllers
{
  [Authorize(Roles = $"{SD.UserRole}")]
  public class ChannelController : CoreController
  {
    public async Task<IActionResult> Index(string stringModel)
    {
      var model = new ChannelAddEdit_vm();
      stringModel = HttpContext.Session.GetString("ChannelModelFromSession");

      if (!string.IsNullOrEmpty(stringModel))
      {
        model = JsonConvert.DeserializeObject<ChannelAddEdit_vm>(stringModel);
        if (model.Errors.Count > 0)
        {
          foreach(var error in model.Errors)
          {
            ModelState.AddModelError(error.Key, error.ErrorMessage);
          }

          HttpContext.Session.Remove("ChannelModelFromSession");

          return View(model);
        }
      }

      var channel = await UnitOfWork.ChannelRepo.GetFirstOrDefaultAsync(x => x.AppUserId == User.GetUserId());
      if (channel != null)
      {
        model.Name = channel.Name;
        model.About = channel.About;
      }

      return View(model);
    }

    [HttpPost]
    public async Task<IActionResult> CreateChannel(ChannelAddEdit_vm model)
    {
      if (!ModelState.IsValid)
      {
        foreach(var item in ModelState)
        {
          if (item.Value.Errors.Count > 0)
          {
            model.Errors.Add(new ModelError_vm
            {
              Key = item.Key,
              ErrorMessage = item.Value.Errors.Select(x => x.ErrorMessage).FirstOrDefault()
            });
          }
        }

        HttpContext.Session.SetString("ChannelModelFromSession", JsonConvert.SerializeObject(model));

        return RedirectToAction("Index");
      }

      var channelNameExists = await UnitOfWork.ChannelRepo.AnyAsync(x => x.Name.ToLower() == model.Name.ToLower());
      if (channelNameExists)
      {
        model.Errors.Add(new ModelError_vm
        {
          Key = "Name",
          ErrorMessage = $"Channel name '{model.Name}' is already taken. Please try another name."
        });

        HttpContext.Session.SetString("ChannelModelFromSession", JsonConvert.SerializeObject(model));
        //return RedirectToAction("Index", new { stringModel = JsonConvert.SerializeObject(model) });
        return RedirectToAction("Index");
      }

      var channelToAdd = new Channel
      {
        AppUserId = User.GetUserId(),
        Name = model.Name,
        About = model.About
      };

      UnitOfWork.ChannelRepo.Add(channelToAdd);
      await UnitOfWork.CompleteAsync();

      TempData["notification"] = "true;Channel created;Your channel has been created and you can upload videos now";

      return RedirectToAction("Index");
    }

    [HttpPost]
    public async Task<IActionResult> EditChannel(ChannelAddEdit_vm model)
    {
      if (ModelState.IsValid)
      {
        var channel = await UnitOfWork.ChannelRepo.GetFirstOrDefaultAsync(x => x.AppUserId == User.GetUserId());
        if (channel != null)
        {
          channel.Name = model.Name;
          channel.About = model.About;
          await UnitOfWork.CompleteAsync();

          TempData["notification"] = "true;Channel updated;Your channel is updated";
          return RedirectToAction("Index");
        }
      }

      TempData["notification"] = "false;Not found;Your channel was not found";
      return RedirectToAction("Index");
    }
  }
}

VideoShare/Controllers/VideoController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using VideoShare.Core.DTOs;
using VideoShare.Core.Entities;
using VideoShare.Core.Pagination;
using VideoShare.Extensions;
using VideoShare.Services.IServices;
using VideoShare.Utility;
using VideoShare.ViewModels;
using VideoShare.ViewModels.Video;

namespace VideoShare.Controllers
{
  [Authorize(Roles = $"{SD.UserRole}")]
  public class VideoController : CoreController
  {
    private readonly IPhotoService _photoService;

    public VideoController(IPhotoService photoService)
    {
      _photoService = photoService;
    }

    public async Task<IActionResult> Watch(int id)
    {
      var toReturn = await GetVideoWatch_vmWithProjections(id);

      if (toReturn != null)
      {
        var userIpAddress = Request.HttpContext.Connection.RemoteIpAddress.ToString();
        await UnitOfWork.VideoViewRepo.HandleVideoViewAsync(User.GetUserId(), id, userIpAddress);
        await UnitOfWork.CompleteAsync();

        return View(toReturn);
      }

      TempData["notification"] = "false;Not Found;Requested video was not found";
      return RedirectToAction("Index", "Home");
    }

    public async Task<IActionResult> CreateEditVideo(int id)
    {
      if (!await UnitOfWork.ChannelRepo.AnyAsync(x => x.AppUserId == User.GetUserId()))
      {
        TempData["notification"] = "false;Not Found;No channel associated with your account. Please create a channel first.";
        return RedirectToAction("Index", "Channel");
      }

      var toReturn = new VideoAddEdit_vm();
      toReturn.ImageContentTypes = string.Join(",", AcceptableContentTypes("image"));
      toReturn.VideoContentTypes = string.Join(",", AcceptableContentTypes("video"));

      if (id > 0)
      {
        // edit
        var userId = await UnitOfWork.VideoRepo.GetUserIdByVideoId(id);
        if (!userId.Equals(User.GetUserId()))
        {
          TempData["notification"] = "false;Not Found;Video not found";
          return RedirectToAction("Index", "Channel");
        }
        var fetchedVideo = await UnitOfWork.VideoRepo.GetByIdAsync(id);
        if (fetchedVideo == null)
        {
          TempData["notification"] = "false;Not Found;Video not found";
          return RedirectToAction("Index", "Channel");
        }
        toReturn.Id = fetchedVideo.Id;
        toReturn.Title = fetchedVideo.Title;
        toReturn.Description = fetchedVideo.Description;
        toReturn.CategoryId = fetchedVideo.CategoryId;
        toReturn.ImageUrl = fetchedVideo.ThumnailUrl;
      }

      toReturn.CategoryDropdown = await GetCategoryDropdownAsync();

      return View(toReturn);
    }

    [HttpPost]
    public async Task<IActionResult> CreateEditVideo(VideoAddEdit_vm model)
    {
      if (ModelState.IsValid)
      {
        bool proceed = true;

        if (model.Id == 0)
        {
          if (model.ImageUpload == null)
          {
            ModelState.AddModelError("ImageUpload", "Please upload thumbnail");
            proceed = false;
          }

          if (proceed && model.VideoUpload == null)
          {
            ModelState.AddModelError("VideoUpload", "Please upload your video");
            proceed = false;
          }
        }

        if (model.ImageUpload != null)
        {
          if (proceed && !IsAcceptableContentType("image", model.ImageUpload.ContentType))
          {
            ModelState.AddModelError("ImageUpload", string.Format("Invalid content type. It must be one of the following: {0}",
              string.Join(", ", AcceptableContentTypes("image"))));
            proceed = false;
          }

          if (proceed && model.ImageUpload.Length > int.Parse(Configuration["FileUpload:ImageMaxSizeInMB"]) * SD.MB)
          {
            ModelState.AddModelError("ImageUpload", string.Format("The uploaded file should not exceed {0} MB",
              int.Parse(Configuration["FileUpload:ImageMaxSizeInMB"])));
            proceed = false;
          }
        }

        if (model.VideoUpload != null)
        {
          if (proceed && !IsAcceptableContentType("video", model.VideoUpload.ContentType))
          {
            ModelState.AddModelError("VideoUpload", string.Format("Invalid content type. It must be one of the following: {0}",
              string.Join(", ", AcceptableContentTypes("video"))));
            proceed = false;
          }

          if (proceed && model.VideoUpload.Length > int.Parse(Configuration["FileUpload:VideoMaxSizeInMB"]) * SD.MB)
          {
            ModelState.AddModelError("VideoUpload", string.Format("The uploaded file should not exceed {0} MB",
              int.Parse(Configuration["FileUpload:VideoMaxSizeInMB"])));
            proceed = false;
          }
        }

        if (proceed)
        {
          string title = "";
          string message = "";

          if (model.Id == 0)
          {
            // create
            var videoToAdd = new Video()
            {
              Title = model.Title,
              Description = model.Description,
              VideoFile = new VideoFile
              {
                ContentType = model.VideoUpload.ContentType,
                Contents = GetContentsAsync(model.VideoUpload).GetAwaiter().GetResult(),
                Extension = SD.GetFileExtension(model.VideoUpload.ContentType)
              },
              CategoryId = model.CategoryId,
              ChannelId = UnitOfWork.ChannelRepo.GetChannelIdByUserId(User.GetUserId()).GetAwaiter().GetResult(),
              ThumnailUrl = _photoService.UploadPhotoLocally(model.ImageUpload)
            };

            UnitOfWork.VideoRepo.Add(videoToAdd);

            title = "Created";
            message = "Video created successfully";
          }
          else
          {
            // for update
            var fetchedVideo = await UnitOfWork.VideoRepo.GetByIdAsync(model.Id);
            if (fetchedVideo == null)
            {
              TempData["notification"] = "false;Not Found;Video not found";
              return RedirectToAction("Index", "Channel");
            }

            fetchedVideo.Title = model.Title;
            fetchedVideo.Description = model.Description;
            fetchedVideo.CategoryId = model.CategoryId; 

            if (model.ImageUpload != null)
            {
              fetchedVideo.ThumnailUrl = _photoService.UploadPhotoLocally(model.ImageUpload, fetchedVideo.ThumnailUrl);
            }

            title = "Edited";
            message = "Video has been updated";
          }

          TempData["notification"] = $"true;{title};{message}"; 
          await UnitOfWork.CompleteAsync();
          return RedirectToAction("Index", "Channel");
        }
      }

      model.CategoryDropdown = await GetCategoryDropdownAsync();

      return View(model);
    }

    public async Task<IActionResult> GetVideoFile(int videoId)
    {
      var fetchedVideoFile = await UnitOfWork.VideoFileRepo.GetFirstOrDefaultAsync(x => x.VideoId == videoId);
      if (fetchedVideoFile != null)
      {
        return File(fetchedVideoFile.Contents, fetchedVideoFile.ContentType);
      }

      TempData["notification"] = "false;Not Found;Requested video was not found";
      return RedirectToAction("Index", "Home");
    }

    #region API endpoints
    //[HttpGet]
    //public async Task<IActionResult> GetVideosForChannelGrid(BaseParameters parameters) 
    //{
    //  var userChannelId = await UnitOfWork.ChannelRepo.GetChannelIdByUserId(User.GetUserId());
    //  var videosForGrid = await UnitOfWork.VideoRepo.GetVi
    //}
    #endregion

    #region Private Methods
    public async Task<IEnumerable<SelectListItem>> GetCategoryDropdownAsync()
    {
      var allCategories = await UnitOfWork.CategoryRepo.GetAllAsync();
      return allCategories.Select(category => new SelectListItem()
      {
        Text = category.Name,
        Value = category.Id.ToString()
      });
    }

    private string[] AcceptableContentTypes(string type)
    {
      if (type.Equals("image"))
      {
        return Configuration.GetSection("FileUpload:ImageContentTypes").Get<string[]>();
      }
      else
      {
        return Configuration.GetSection("FileUpload:VideoContentTypes").Get<string[]>();
      }
    }

    private bool IsAcceptableContentType(string type, string contentType)
    {
      var allowedContentTypes = AcceptableContentTypes(type);
      foreach (var allowedContentType in allowedContentTypes)
      {
        if (contentType.ToLower().Equals(allowedContentType.ToLower()))
        {
          return true;
        }
      }

      return false;
    }

    private async Task<byte[]> GetContentsAsync(IFormFile file)
    {
      byte[] contents;
      using var memoryStream = new MemoryStream();
      await file.CopyToAsync(memoryStream);
      contents = memoryStream.ToArray();
      return contents;
    }

    private async Task<VideoWatch_vm> GetVideoWatch_vmWithProjections(int id)
    {
      int userId = User.GetUserId();
      var toReturn = await Context.Video
        .Where(x => x.Id == id)
        .Select(x => new VideoWatch_vm
        {
          Id = x.Id,
          Title = x.Title,
          Description = x.Description,
          ChannelId = x.ChannelId,
          ChannelName = x.Channel.Name,
          CreatedAt = x.CreatedAt,
          ViewersCount = x.Viewers.Count
        })
        .FirstOrDefaultAsync();

      return toReturn;
    }
    #endregion
  }
}

VideoShare/Views/Channel/Index.cshtml
@model VideoShare.ViewModels.Channel.ChannelAddEdit_vm

@if (string.IsNullOrEmpty(Model.Name) || Model.Errors.Count > 0) {
  <p>You don't have any channels yet. Use the form bellow th create your channel.</p>
  <form asp-action="CreateChannel" class="mt-2">
    <div class="row">
      <div class="col-md-6">
        <div class="mb-3">
          <label asp-for="Name" class="form-label"></label>
          <input asp-for="Name" type="text" class="form-control" />
          <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="mb-3">
          <label asp-for="About" class="form-label"></label>
          <textarea asp-for="About" rows="6" class="form-control"></textarea>
          <span asp-validation-for="About" class="text-danger"></span>
        </div>
        <button class="btn btn-success" type="submit">Create</button>
      </div>
    </div>
  </form>
}
else 
{
  <ul class="nav nav-tabs">
    <li lcass="nav-item">
      <a class="nav-link" data-bs-toggle="tab" href="#myvideos">My Videos</a>
    </li>
    <li lcass="nav-item">
      <a class="nav-link" data-bs-toggle="tab" href="#analytics">Analytics</a>
    </li>
    <li lcass="nav-item">
      <a class="nav-link" data-bs-toggle="tab" href="#profile">Profile</a>
    </li>
  </ul>
  <div class="tab-content">
    <div class="tab-pane fade" id="myvideos">
      <div class="mt-3">
        <a class="btn btn-primary" asp-controller="Video" asp-action="CreateEditVideo">Create Video</a>
      </div>
    </div>
    <div class="tab-pane fade" id="analytics">
      <div class="mt-3">
        Analytics
      </div>
    </div>
    <div class="tab-pane fade" id="profile">
      <div class="mt-3">
        <form asp-action="EditChannel" method="post">
          <div class="row">
            <div class="col-md-6">
              <div class="mb-3">
                <label asp-for="Name" class="form-label"></label>
                <input id="profile_name" asp-for="Name" type="text" class="form-control" disabled />
                <span asp-validation-for="Name" class="text-danger"></span>
              </div>
              <div class="mb-3">
                <label asp-for="About" class="form-label"></label>
                <textarea id="profile_about" asp-for="About" type="text" class="form-control" rows="6" disabled></textarea>
                <span asp-validation-for="About" class="text-danger"></span>
              </div>
              <div class="row" id="divEditButton">
                <div class="col">
                  <div class="d-flex justify-content-end">
                    <button type="button" class="btn btn-outline-secondary" onclick="editProfile()">Edit</button>
                  </div>
                </div>
              </div>
              <div class="row" id="updateProfileButtons" style="display: none;">
                <div class="offset-3 col-6">
                  <div class="row">
                    <div class="col d-grid">
                      <button class="btn btn-success" type="submit">Update</button>
                    </div>
                    <div class="col d-grid">
                      <button class="btn btn-danger" type="button" onclick="cancelEdit()">Cancel</button>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
}

@section Scripts {
  <partial name="_ValidationScriptsPartial" />
  <script>
    $(function () {
      $('a[data-bs-toggle="tab"]').on('shown.bs.tab', function (e) {
        var currentTabId = $(e.target).attr('href');
        localStorage.setItem('activeTab', currentTabId);
      });

      var activeTab = localStorage.getItem('activeTab');
      if (activeTab) {
        $('a[href="' + activeTab + '"]').tab('show');
      } else {
        $('a[href="#myvideos"]').tab('show');
      }
    });

    function editProfile() {
      $('#updateProfileButtons').show();
      $('#profile_name').prop("disabled", false);
      $('#profile_about').prop("disabled", false);
      $('#divEditButton').hide();
    }

    function cancelEdit() {
      $('#divEditButton').show();
      $('#updateProfileButtons').hide();
      $('#profile_name').val('@Model.Name');
      $('#profile_about').val('@Model.About');

      $('#profile_name').prop("disabled", true);
      $('#profile_about').prop("disabled", true);

      $('#profile_name-error').empty();
      $('#profile_about-error').empty();
      $('#profile_name').removeClass('input-validation-error');
      $('#profile_about').removeClass('input-validation-error');
    }
  </script>
}